services:
  dev:
    env_file:
      - ./.env
    build:
      context: .
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    profiles: [dev]

  prod:
    build:
      context: .
      target: prod
      args:
        VITE_NEWS_API_KEY: ${VITE_NEWS_API_KEY}
        VITE_THE_GUARDIAN_API_KEY: ${VITE_THE_GUARDIAN_API_KEY}
        VITE_NEW_YORK_TIMES_API_KEY: ${VITE_NEW_YORK_TIMES_API_KEY}
    ports:
      - "8080:80"
    profiles: [prod]
